In [1]:
# Importing the Libraries

import yfinance as yf
import pandas as pd
# import matplotlib.pyplot as plt
import requests

In [2]:
# API Key
api_key = 'JX03FL2W87N81TEN'

# API
url = f'https://www.alphavantage.co/query?function=FX_DAILY&from_symbol=EUR&to_symbol=USD&outputsize=full&apikey={api_key}&datatype=csv'

#API request send
response = requests.get(url)

# Convert to DataFrame
from io import StringIO
df = pd.read_csv(StringIO(response.text))

In [3]:
# Printing first 5 rows of df
df.head()

    timestamp     open     high      low    close
0  2025-05-09  1.12268  1.12929  1.11964  1.12460
1  2025-05-08  1.13120  1.13362  1.12116  1.12261
2  2025-05-07  1.13721  1.13782  1.12914  1.13106
3  2025-05-06  1.13157  1.13811  1.12796  1.13715
4  2025-05-05  1.12990  1.13648  1.12968  1.13143

In [4]:
# Printing last 5 row of df
df.tail()

       timestamp    open    high     low   close
4995  2006-03-16  1.2068  1.2189  1.2032  1.2179
4996  2006-03-15  1.2011  1.2074  1.2003  1.2068
4997  2006-03-14  1.1961  1.2031  1.1936  1.2010
4998  2006-03-13  1.1914  1.1969  1.1908  1.1957
4999  2006-03-10  1.1911  1.1931  1.1857  1.1913

In [5]:
# Number of rows and columns
df.shape

(5000, 5)

In [6]:
# Data Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  5000 non-null   object
 1   open       5000 non-null   float64
 2   high       5000 non-null   float64
 3   low        5000 non-null   float64
 4   close      5000 non-null   float64
dtypes: float64(4), object(1)
memory usage: 195.4+ KB

There are no null/missing values in the data

In [109]:
# Converting 'timestamp' to datetime
df['timestamp'] = pd.to_datetime(df['timestamp'])

# selecting relevant column and renaming them
df = df[['timestamp', 'close']]
df = df.rename(columns={'timestamp': 'Date', 'close': 'EURUSD'})

df.set_index('Date', inplace=True) # to remove serial number
df

             EURUSD
Date
2025-05-09  1.12460
2025-05-08  1.12261
2025-05-07  1.13106
2025-05-06  1.13715
2025-05-05  1.13143
...             ...
2006-03-16  1.21790
2006-03-15  1.20680
2006-03-14  1.20100
2006-03-13  1.19570
2006-03-10  1.19130

[5000 rows x 1 columns]

#Plotting
plt.figure(figsize=(12,6))
plt.plot(df['Date'], df['EURUSD'], color='gold', linewidth=2)
plt.title('EUR/USD Exchange Rate Over Time', fontsize=17)
plt.xlabel('Date', fontsize=13)
plt.ylabel('Exchange Rate EUR to USD', fontsize=13)
plt.grid(True)
plt.tight_layout()
plt.show()

In [110]:
df.to_csv('EURUSD.csv')
print('Daten wurden erfolgreich als CSV gespeichert.')

Daten wurden erfolgreich als CSV gespeichert.